### ISSUE TITLE
The Issues Issue

### ISSUE THREAD

**Issue by deanishe** [shawnrice/alfred-bundler#28]
#### In which we address the Issue organising issue
- Are the current labels appropriate?
- How should we group/organise the labels?
- How should we _use_ GitHub's issue system?
- Is there a better way of organising the roadmap than using GitHub issues?
- How much wood would a woodchuck chuck if Alfred supported nodejs?

Add your input in this Issue and we can formalise it either in this OP or a Markdown doc in the repo.

**Comment by shawnrice** [comment]
Wait, you want to add nodejs as an asset?

**Comment by deanishe** [comment]
Fuck no!

Also, how do you add labels? I wanted to add a "meta" label, but I don't know how :disappointed:

**Comment by shawnrice** [comment]
Go to the regular "issues" page, then click the "labels" tab. Then add/edit labels and colors.

To label add labels in a particular issue, look to the upper right side of this and select / de-select whichever issues you deem appropriate.

**Comment by deanishe** [comment]
OTOH, although that nodejs comment was entirely fatuous, _would_ it be worth considering adding additional execution environments (`nodejs`, `Go`) to the bundler?

It would make implementing title case servers so much easier.

**Comment by deanishe** [comment]
> Go to the regular "issues" page, then click the "labels" tab. Then add/edit labels and colors.

Shweet. I've assigned the `meta` tag with an appealing vomit colour.

**Comment by shawnrice** [comment]
Instead of a markdown file, we could use the wiki. 

Otherwise, we could have the large meta issue for bigger projects. The meta issue has the advantage of automatically linking to other issues (#15) with the number but not the name.

**Comment by shawnrice** [comment]
Okay, @deanishe knows this well, and I'm sure that @Ritashugisha is figuring this out: I have a tendency to be (unnecessarily) verbose. Here, I'm pledging that if I write way too much in any single issue, I'll add a **TL;DR** tag at the top of the OP with a terse summary.

**Comment by shawnrice** [comment]
### Two kinds of "use" labels
1. Labels that help us track development that we use internally; and
2. Labels that other people might use to report bugs / suggest features.

#### Internal Labels

It might be best to think about labels in terms of "sets."

##### Set 1: Bundler Implementation Labels

These should be obvious.
- Bash
- Misc
- PHP
- Python
- Ruby

##### Set 2: Version Labels

Right now, we're using milestones for development, which makes sense. I created the "Far Future" label so that we can log the idea and ignore it for now. We could continue to use milestones for development (Taurus 1, Taurus 2, Gemini, Gemini 1, Gemini 2, etc...). This is a good idea for development, but it might not work well for user oriented labels (obviously, users will try to use these labels).

So, possible version labels:
- Aries
- Taurus
- Gemini
- Devel

##### Set 3: Component Labels

It's also useful to think of the bundler in terms of components. These would either be scripts that are shared between the bundler. I've started to outline the idea [on the wiki](https://github.com/shawnrice/alfred-bundler/wiki/Components).
- Gatekeeper
- Registry
- JSON Assets (better title needed here)
- Default Assets
- Icons
- Bindings (this should be split into a label per binding)
- Tests

##### Set 4: Status Labels

These are temporary labels that let us track the status of the issue. Currently:
- Needs Discussion
- Needs Work
- Needs Review
- Needs Testing
- Release Blocking (this should be tagged only on issues with milestones)
- Started

##### Set 5: Misc
- meta

#### User Labels

The ones that GH provides by default are pretty helpful for the overall "status" of the issue.

###### Set 1: Kind of Report
- Enhancement
- Feature
- Bug
- Question

##### Set 2: Responses

The set of responses that we have are just ones to shut down the issue quickly.
- Duplicate
- Invalid
- Wont Fix

### Further discussion

Are these adequate? How do you feel about the divisions of the labels above as "sets"? Are there sets that are incomplete?

**Comment by shawnrice** [comment]
RE: OP: we should outline a taxonomy of these in the README.md as well as in the OP. I wish we could make a "sticky" issue or something.

We can also put a copy [in the wiki](https://github.com/shawnrice/alfred-bundler/wiki/Reporting-Issues).

**Comment by shawnrice** [comment]
For now, I'm going to close the issues tagged with `Far Future`. After we release Taurus, then we can open them back up. This way it helps in that once the issue queue is empty, Taurus is pushed.

**Comment by shawnrice** [comment]
I'm closing this for now. The only issues that I want open are the ones that are blocking Taurus. We can always open it up again, but we should, perhaps, move things over to [this wiki page](https://github.com/shawnrice/alfred-bundler/wiki/Reporting-Issues) or somehow integrate it into the documentation.

**Comment by deanishe** [comment]
Set up a milestone

**Comment by shawnrice** [comment]
For the documentation?

**Comment by deanishe** [comment]
I meant for the release, but I see you already have done. As an alternative to closing issues.
