### ISSUE TITLE
AlfredBundler::load error

### ISSUE THREAD

**Issue by deanishe** [shawnrice/alfred-bundler#43]
Calling the misc bundler directly, I'm getting the following error:

```
./alfred.bundler.misc.sh: line 42: `AlfredBundler::load': not a valid identifier
```

I'm afraid I'm not very familiar with the new bundler. Any idea what's going wrong?

**Comment by shawnrice** [comment]
9cf34ba3228470d7d1c157e7176a3087c47cedae fixes it.

Turns out that the top of the script really needed to be `#!/bin/bash` rather than `#!/bin/sh`.

Also, I noticed that you changed the install URL away from the tag to the repo. Is this just for development so that we don't have to keep pushing the tags?

**Comment by deanishe** [comment]
> Turns out that the top of the script really needed to be #!/bin/bash rather than #!/bin/sh

:smiley:

Now I'm getting this error:

```
cat: /Volumes/Users/daj/Library/Application Support/Alfred 2/Workflow Data/alfred.bundler-devel/data/assets/utility/Terminal-Notifier/default/invoke: No such file or directory
```

It isn't installing Terminal-Notifier (or anything else for that matter).

> Also, I noticed that you changed the install URL away from the tag to the repo. Is this just for development so that we don't have to keep pushing the tags?

Yup.

**Comment by shawnrice** [comment]
Strangely, it was working just about fine for me yesterday. Now it's sending me the same errors. I'm on it.

**Comment by shawnrice** [comment]
797112ab86fc8c1dc530776d625d8a33358567bd fixes it.

And that's what happens when I'm testing this from too many different parts of the bundler and not fully cleaning the directories beforehand: I forget to re-implement the install logic for the utilities (it was there for non-utilities).

There's an issue with the icons right now on the misc bundler that I'm playing with right now.

**Comment by shawnrice** [comment]
Nevermind. The issue with icons was user error (read: me typing the wrong thing into the command line).
