### ISSUE TITLE
Pop up keep asking to install required software

### ISSUE THREAD

**Issue by vdesabou** [shawnrice/alfred-bundler#5]
Hi Shawn,

I'm using your bundler to have an updated version of terminal-notifier 1.6.0 whereas default one is 1.5.0 (BTW that would be great to have this one by default :) it adds support of contentImage. For some reason, version 1.5.0 is in release but not the 1.6.0, which is the one when you download the project. If you want it there is a version here https://github.com/vdesabou/alfred-spotify-mini-player/blob/master/bundler/terminal-notifier.app.zip 

Anyway, back to my problem..
So I have a json here https://github.com/vdesabou/alfred-spotify-mini-player/blob/master/bundler/Terminal-Notifier-Version-1.6.json

And I use it like this:

```
    // Load and use Terminal Notifier, a "helper" utility
    $tn = __load('Terminal-Notifier-Version-1.6' , '1.6.0' , 'utility', './bundler/Terminal-Notifier-Version-1.6.json' );
    exec( "$tn -title 'Spotify Mini Player' -sender 'com.spotify.miniplayer' -message '" . $output . "'" );
```

It was working fine until now but I've removed the data directory for the bundler to fix another issue, so I guess I have now the latest version of bundler in there

Now I constantly get this popup window:

![screenshot_2014-07-02_10 10 15](https://cloud.githubusercontent.com/assets/4061923/3453173/828b6468-01c0-11e4-8d49-8b901f005cb0.png)

Looks like the version 1.6.0 is installed because I get notifications as expected, it's just that I have this popup every time.

I've uploaded here the bundler data folders (old-> was working, new-> have this issue with popup asking every time to install version 1.6.0)
https://cloudup.com/cBAHL3uXp7u

Thanks!

**Comment by shawnrice** [comment]
It looks like there is a problem with it getting cached and getting listed with spctl. It's probably either an invalid character for spctl or a problem with the way that we're implementing the custom JSON loading. I'll look into it. @deanishe, let me know if you come across the problem first.

**Comment by shawnrice** [comment]
So, the problem is that Gatekeeper is returning a path not found error. The script is expecting that the name of the application is the name in the JSON, not an alias, so the Gatekeeper script kept looking for something else.

Good news: I found a bug with the caching and fixed that while I was in there.

Also good news: I added in terminal notifier 1.6.0 into the defaults. 

If you want to ensure that your users can get it, then go ahead and add in your own JSON, but, basically, keep the regular TN JSON and just strip out the default and 1.5.0 versions and add in a 1.6.0 version and use that.
