### ISSUE TITLE
Common cache?

### ISSUE THREAD

**Issue by deanishe** [shawnrice/alfred-bundler#52]
Some of the bundlers cache the results of expensive operations.

Is it worthwhile to implement a common cache format across bundlers, so that each bundler can benefit from the work already done by others?

Obviously, this would tie the bundlers quite closely together, and will likely mean suboptimal performance in one or more implementations. Both are things I'm broadly against, but the performance advantage may outweigh the downsides.

The Python bundler currently saves altered colours in the bash bundler's cache, mostly as a courtesy to its sibling, but uses its own cache for everything else, such as utility paths.

What do you folks reckon is the best thing to do?

**Comment by shawnrice** [comment]
Currently, we have the `call-cache` and the `color-cache`, which use practically the same methods that do create and use the same data, so we'd be dolts not to keep those as common caches.

The `call-cache` is there to make utilities easier to load (in passing checks with gatekeeper), but the format is the simple hash one that you @deanishe worked out, and there is no reason why it shouldn't be shared.

The `color-cache` just holds the color conversions with very, very simple information that each language can read. So, obviously that should be a shared cache too.

So, both of these are, intelligently, common caches. Are there non-common caches?

I know that I implemented a `composer` cache for PHP. Well, basically if just makes double-checks that the `composer` json called each time is the same that already exists so that `composer` doesn't need to run again. But these are workflow-specific caches.

There is a Python `pip` caching mechanism, right? It works like the composer one I mentioned?

Are there any others?

While this project does seem like it's four (or five) different ones put together, it really is more of a single project with five interfaces, and so anything that can be shared without slowing performance, should be shared.

**Comment by deanishe** [comment]
> the format is the simple hash one that you @deanishe worked out

Aye, but it was specifically conceived for bash, loosely based on the model the Python bundler was already using. The Python bundler is still using its own, older caching mechanism, which is specifically designed to allow it to be applied (transparently as a decorator) to any bundler function (although it's currently only used to cache the results of `utility()`).

There are two other distinct caching mechanisms for `pip` that cache metadata, not data: there's one that recognises when an HTTP resource has been updated, and another (workflow-specific) one that recognises when `requirements.txt` has been updated.

Supporting common caches would require implementing separate caching logic for every function that should be cached, unless the bash bundler is also standardised around a `name/md5-hash-of-args` cache model.

If we can come up with a standard caching mechanism that can be implemented across bundlers _and_ functions, that'd be a no-brainer to use.

Assuming all the bundlers accept the same arguments, an md5 hash of the functions should do the trick.

**Comment by shawnrice** [comment]
Well, we could do the same. I can implement a cozy little method/function in the other bundlers that would work like:

```
function read_cache() {
# $1 = cache
# $2 = key
if [ -d "${AB_DATA}/data/${cache}-cache" ]; then
  if [ -f "${AB_DATA}/data/${cache}-cache/${key}" ]; then
    echo $(cat "${AB_DATA}/data/${cache}-cache/${key}")
   return 0
  else
    return 1
  fi
fi
}

function write_cache() {
# $1 cache
# $2 val
# the rest of the arguments are the key components
  key=''
  i=3
  max=$(( $# - 2 ))
  while [[ $i -lt $max ]]; do
      key="${key}-"$[$i]
      i=$[$i+1]
  done
  key=$(echo $key | md5)
  echo $val > "${AB_DATA}/data/${cache}-cache/${key}"
}
```

The code is untested, doesn't have error checking, and probably could be simplified, but that would allow us to have the generic caching function that would follow python.

Good?

**Comment by deanishe** [comment]
I edited my previous comment a bit, but it isn't overly relevant.

First off, it's impossible for bash (or any other language) to utilise the Python cache format, as it uses serialised Python data.

What we can do, however, is implement an md5 hash-based caching mechanism.

We generate a hash of the arguments, e.g. `hash(arg1-arg2-arg3)`, and use that as the filename, saved under a directory corresponding to the function:

```
cache-utility/
    asd4a4a4w005gjl434353faw44r
    gfg353tjlk3jtfnfn43roi34r43nr34r
    …
cache-color/
    4534wmaf34ptofj43or3n434orh3
    0uihgaslkfnawnk4jnrafjbsakj2239
    …
```

The cached value is stored as the contents of the file. The disadvantage for languages that support proper serialisation is that everything must be a string.

**Comment by shawnrice** [comment]
Those preliminary bash functions should carry out what you just wrote. The only question then is whether the string / serialized data would have different outputs. As long as the key is the same and the contents can be read by every language, then it should be fine.

That means that we'd have to store everything in the files themselves as plain-text (preferably a single line), but that actually makes it easier for each language (I think) because it removes one or two function calls to be able to use the data.

Obviously for language specific caches (especially those for `Pip`, `Gem`, and `Composer`) can be written in JSON or however else.

So, @deanishe the product of the serialized data and the string would be the same, right?

**Comment by shawnrice** [comment]
Okay, let's formalize this a bit more. Here's a detailed pseudo-proposal.

#### Common Cache

##### Locations

The common cache directory should live in one of two places:
1. `{ab_cache_dir}/common`
2. `{ab_data_dir}/data/caches`

I'm fine with either. Regardless, the common cache__s__ get their own sub directories. So, say we go with the second option from above, then we'd have
Color cache: `{ab_data_dir}/dir/caches/color`
Call: `{ab_data_dir}/dir/caches/call`

Sidenote: I think we should change the `call` cache to something like `path` cache or `util` cache.

We actually should consider certain global variables that we have as common caches. These, currently, are:
1. `theme_background`
2. `update` (to check for minor updates to the bundler)

Since the latter cache will never be larger than a single file, they should stay within the root of the common cache directory. The names shouldn't be hashed.

##### Cache Keys
1. The cache key should use the minimum number of arguments possible in order not to clash
2. The cache key should have each argument separated with a `-`
3. The keys should be simple `md5` hashes of the above string.

So, for the current call cache, we have: 
`{$name}-{$version}-{$type}-{$json}`

For the color cache, we have:
`{$hex}`, where `$hex` is six characters without the #.

##### Language Specific Caches

Each language cache can have it's own methods of caching as the logic for each cache is entirely separate from each other implementation. Hence, the current language caches that we have are:

**Bash**
- None

**PHP**
- Composer

**Python**
- Pip 
  - Pip updates
  - Changes to workflows' Python dependencies

**Ruby**
- Gem (or I need to implement it... the Ruby bundler is pretty far behind).

We should, however, have a common place for these to live. Maybe something like:
`{ab_cache_dir}/specific/{language}/whatever-sub-cache`. So, PHP's composer cache would be found at `{ab_cache_dir}/specific/php/composer/{sub_caches}`. 

The other way that we could go about it is a "per-workflow" cache. So, let's image a Frankenstein workflow that is unequal parts Bash, PHP, Python, and Ruby. The latter three implement the respective bundlers, utilizing `Composer`, `Pip`, and `Gems`. Then, we would have something like:
`{ab_cache_dir}/workflows/{bundleid}/etc....`, which is where we would cache anything we in sub-directories. 

So, it would have something like:
- `{ab_cache_dir}/workflows/com.frankenstein/composer/...`
- `{ab_cache_dir}/workflows/com.frankenstein/pypi-packages/...`
- `{ab_cache_dir}/workflows/com.frankenstein/gems/...`

##### Asset Caches

While most assets won't recognize that they are existing as part of the bundler, there may be some that are developed specifically for bundler use.

Here, I'm thinking of the emoji "add-on" thing. It seems like it would be best for that to have its own cache, but it should live in the bundler's cache because it is so separate. Let's set aside a specific directory to contain these caches. I'm thinking: `{ab_cache_dir}/assets/`.

Then each would have their own sub-directory, so emoji would have: `{ab_cache_dir}/assets/emoji`.

##### Generated files

The bundler has the ability to generate certain files. Here, I'm mostly thinking of the `icns_to_png.sh` and `png_to_icns.sh` scripts. These should be cached somewhere, and that where depends on the logic of the method. So, it seems like some methods would make sense to store the file in the implementing workflow's data or cache directory. But, we might need to store it in a bundler cache directory.

If we generate files that are workflow specific, then we could consider using the workflow cache model describe above.

If we generate more general files, then we might consider caching these like the proposed asset cache.

**Comment by deanishe** [comment]
Emoji, FFS :grinning: 

If you're hell-bent on having emoji _and_ want a cache for it, you might as well just implement it as the cache, i.e. on install, every available emoji is cached and the cache becomes the primary data store.

**Comment by deanishe** [comment]
As in other situations, I'd prefer to keep Python stuff separate from other implementations, so:

```
{ab_data_directory}/
    workflows/
        com.frankenstein/
            python/
                libs/
                …
            ruby/
                gems/
                …
            php/
                composer/
                …
```

rather than 

```
{ab_data_directory}/
    workflows/
        com.frankenstein/
            pypi-packages/
            composer/
            …
```

Ideally, I'd like to put everything Python-related under a single `{ab_data_directory}/python/…` to make it easier to delete all the Python data when there's a problem with the Python bundler, but that would make things much more complicated if we want to create an uninstaller script in the future.

So I suggest the above compromise that would again free up different bundlers to organise their stuff in a way that makes most sense.

I'll be keeping the Python-specifc caches in the data directory, as they're basically metadata, not cached data per se.

The common caches can go in `{ab_cache_dir}`, alongside bundler-specific caches (should they be needed):

```
{ab_cache_dir}/
    bash/
        …
    colors/
        ...
    php/
        …
    python/
        …
    ruby/
        …
    utilities/
        ...
```

Are there any other common caches apart from `colors` and `utilities`?

Individual bundlers should have their own directories under `{ab_data_dir}/assets` with which they can do as they please:

```
{ab_data_dir}/
    assets/
        icons/
            ...
        utility/
            ...
        python/
            …
        php/
            …
        ruby/
            …
```

In the case of the Python bundler, for example, this is where I would install `pip`.

**Comment by shawnrice** [comment]
Yes to keeping the asset directory the same. That seems like it has worked out so far, and I don't see any problems with it.

I'm down with the compromise version. Currently, there are no common caches, besides the ones mentioned, that would require a directory. Let's add one more directory in the `{ab_cache_dir}` for cached values that are single files. The only two that exist for that now are `update` and `theme_background`, although `theme_background` at this point is becoming deprecated because of v2.4:277, although we need to continue to support it.

As far as I know, the only other directories used in the `{ab_cache_dir}` are temporary ones that are deleted after use. There is one to install the bundler, one to update the bundler, one to download utilities before installing them, and one for `composer` installations. Respectively, these are:

```
- alfred-bundler-{major-name}-latest
- update
- installers
- composer
```

But, again, these directories are deleted after use. The only reason that they would exist after the bundler has run an operation is if the operation has failed, although, with new error handling, these are cleaned as best as possible.

I'm assuming that the `call-cache` changed into `utilities`?

So, new directory structure:

```
{ab_cache_dir}/
    bash/
        …
    colors/
        ...
    php/
        …
    python/
        …
    ruby/
        …
    utilities/
        ...
    etc/
        ...
```

Cool?

**Comment by deanishe** [comment]
`etc/`?

**Comment by shawnrice** [comment]
At first I went to `misc`, but then that might be the `misc` bundler. Now that the `misc` is gone, let's use `misc` instead of `etc`

**Comment by deanishe** [comment]
`misc/`?

**Comment by shawnrice** [comment]
`misc/`.

Here's another one that we need to do: `icns`. Right now the `icns` method in the PHP bundler (the one that will create an `icns` file from a `png`) stores anything in `icns`.... Maybe the common cache could have a folder:

```
{ab_cache_dir}
images/
  -- icns/
    -- {bundleid} 
```

**Comment by deanishe** [comment]
I must admit I don't know how these `icns` files come to be. Which part of the bundler creates these?

Shouldn't they go in `{ab_data_dir}` along with the PNG files?

**Comment by shawnrice** [comment]
There's a method in the PHP bundler that's just called `icns`, and it just wraps around the `png_to_icns.sh` script. It's just a little easter egg in that I wanted to use it for the Gatekeeper scripts. I figured that, since the functionality was always coded, we could easily provide a wrapper function to let others use it.

Current functionality:

```
$b = new AlfredBundler;
echo $b->icns(); // converts the icon.png to icon.icns and returns the path.
echo $b->icns( 'path/to/png.png' ); // converts chosen png to icns and returns the path.
```

They could go in the data directory along with PNG files, but I've been considering them workflow specific, so as the cache because they don't really seem to be _shared_ assets. They could go in `{ab_data_dir}`, but we'd need to create a workflow-specific subdir for these sorts of things.

So, in my mind, I have a distinction between generated assets and downloaded assets. Downloaded live in the directory, and generated live in the cache, but, I'm just figuring out that it's an internal bias that isn't substantiated. I can go either way, but we should have a dedicated place for them.

**Comment by shawnrice** [comment]
Okay. I'm closing this issue.

Decision: download data goes into the data directory. Generated data goes into the cache directory. Any new common caches needed in the future should do one of the following:
1. If it is a single file cache, then it goes in `misc`
2. If it needs more than one file cached, then it gets its own in the `cache` directory.

Any new caches needing discussion and implementation across the Bundler at large should get their own issue.
