### ISSUE TITLE
Separate Python Bundler into Wrapper / API

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#6]

**Comment by deanishe** [comment]
Pretty much done bar the shouting.

Still to do:
- [x] Strip down download function in wrapper.
- [x] Move all update metadata handling to the bundler from the wrapper (by the time the installation code in the wrapper completes, the bundler library will be available and importable).

I think that's about it for this issue. Please edit if otherwise.

**Comment by deanishe** [comment]
Closing as done.
