### ISSUE TITLE
Applescript Bundlet

### ISSUE THREAD

**Issue by fractaledmind** [shawnrice/alfred-bundler#68]
AppleScript Bundler/Bundlet TODO:
- [x] Write native `_bootstrap()` function  
- [x] Write unit tests  
- [x] Delete cached bundler after installation  
- [x] Add documentation for all bundler handlers (even helper handlers)  
- [x] Ensure error messages and numbers are consistent with Bash Bundler (at least)
- [x] Document available AppleScript `libraries`  
- [x] Refactor logging line numbers

**Comment by fractaledmind** [comment]
You can now at least see my code on my fork of this repo: https://github.com/smargh/alfred-bundler/blob/as_devel/bundler/

And here's the uncompiled version of my Applescript bundlet: https://github.com/smargh/alfred-bundler/blob/as_devel/bundler/bundlets/bundler.applescript

**Comment by shawnrice** [comment]
I might have changed something in the Bash bundlet that would break the Python bundlet's install method: the bash bundlet now follows the rest of the other bundlets in that it won't work unless there is an `info.plist` file at the `.` of where the script is being run.

The problem might be in a quirk of the language: how does Applescript's `do shell script` actually work? If it opens up a subshell and then changes to the script directory to run it, then it'll have this bad, bad problem. Does it work like that?

The `Print: Entry, \":name\", Does Not Exist` error comes from PlistBuddy complaining that the plist key doesn't exist (which might also mean the plist itself).

You can get rid of some of the python specific quirks. For instance, the Python helpers library exists only because of how Pip works.

**Comment by fractaledmind** [comment]
That makes sense. And the new logic of the bash bundlet definitely breaks the current `bundler.py`. Instead of temporarily installing the bash bundlet in the cache dir, but Python and AppleScript bundlets should install in temporarily in the workflow folder.

**Comment by shawnrice** [comment]
What should happen is that, if the Python and AppleScript bundlets want to use the Bash bundlet to install the bundler, they should have to have the bash bundlet included in the workflow along with the other bundlet.

I think that, from #61, the Python bundlet needs to be rewritten to have its own install function. Right now the Bash, PHP, and Ruby bundlets have a native install function that allows for fallback servers so that if Github is unreachable, then it goes to Bitbucket (and it will go to another one or two when I set them up).

Take a closer look at the bash bundlet to see how the install function works there (the PHP and Ruby ones are class-based). I think that the AppleScript bundlet should be modeled on the Bash one because Bash is the most similar to AppleScript when it comes to this sort of implementation.

**Comment by shawnrice** [comment]
(Granted, the Bash bundlet is a hollow shell because many of the functions are just overwritten by the Bash bundler, so that doesn't transfer to the AppleScript version -- unless AS does the same thing when you redeclare a function).

The AppleScript bundlet should also follow a more Bash-like naming prefix in order to avoid function and variable clashes. Ruby has an `Alfred` namespace that prevents a clash, and PHP has the `AlfredBundler` class that prevents the clash. I know that Python does something to prevent it as well (right?). The Bash prefix `AlfredBundler::` is just the same as `AB_` or anything like that.

**Comment by fractaledmind** [comment]
I don't see why prefixed function names are necessary in AppleScript. For the workflow author using this bundlet, he would have to load the whole script into a variable and then access function via that scope, e.g.:

```
set bundler to load script "alfred.bundler.scpt"
bundler's notify()
-- versus an internal function
my write_to_file()
```

So scopes are explicitly set via the possessive. This seems to perform the same functionality of explicitly prefixed functions

**Comment by shawnrice** [comment]
Well, that means they don't need to be prefixed at all. See, this is why I didn't try to write an AppleScript implementation: I don't _really_ know how the language works. Good job. No prefixes.

**Comment by fractaledmind** [comment]
Great. So, I've just pushed `AlfredBundler.scpt`/applescript and `aflred.bundler.scpt`/applescript to the `devel` branch. You will see that I'm working on the `get_icon()` and `load_utility()` functions in `AlfredBundler.scpt`. It's fairly trivial to check if an item exists, but when I try to pass it on the the `alfred.bundler.sh` file in the bundlets sub-directory, I get this dialog:
![screen shot 2014-08-21 at 6 01 03 pm](https://cloud.githubusercontent.com/assets/5077225/4015104/de735b84-2a27-11e4-8722-ffb5d6687ea6.png)

Now, there is an `info.plist` file right next to `alfred.bundler.sh`, so I have no idea what isn't right. Clearly, the name of the workflow is wonky. Plus, if I press `Proceed`, the icon file is not created. 

Any help?

**Comment by fractaledmind** [comment]
As far as I can tell, its a problem with the bash bundler. Or am I missing something?

**Comment by fractaledmind** [comment]
Whenever I just run the `alfred.bundler.sh` file (from CodeRunner), I get these messages:

```
Installing Alfred Dependency Bundler version 'devel' ...
Fetching https://github.com/shawnrice/alfred-bundler/archive/devel-latest.zip ...
curl: (22) The requested URL returned error: 404 Not Found
[OK] https://github.com/shawnrice/alfred-bundler/archive/devel-latest.zip
[bundler.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of bundler.zip or
        bundler.zip.zip, and cannot find bundler.zip.ZIP, period.
Alfred Bundler Install Error: Installation zipfile is corrupted.
Exiting Bundler installation...
alfred.bundler.sh: line 352: return: can only `return' from a function or sourced script
```

**Comment by fractaledmind** [comment]
I am using the up-to-date version from the `devel` branch

**Comment by fractaledmind** [comment]
Finally, these are the results of running the Applescript command (`cmd`) from the Terminal:

```
Last login: Fri Aug 22 14:02:54 on ttys000
Macintosh-5:~ smargheim$ /bin/bash '/Users/smargheim/Documents/DEVELOPMENT/GitHub/alfred-bundler/bundler/bundlets/alfred.bundler.sh' utility pashua latest false
Alfred Bundler Error.... need an info.plist to use the bundler.
Print: Entry, ":name", Does Not Exist
Installing Alfred Dependency Bundler version 'devel' ...
Fetching https://github.com/shawnrice/alfred-bundler/archive/devel-latest.zip ...
curl: (22) The requested URL returned error: 404 Not Found
[OK] https://github.com/shawnrice/alfred-bundler/archive/devel-latest.zip
[bundler.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of bundler.zip or
        bundler.zip.zip, and cannot find bundler.zip.ZIP, period.
Alfred Bundler Install Error: Installation zipfile is corrupted.
Exiting Bundler installation...
/Users/smargheim/Documents/DEVELOPMENT/GitHub/alfred-bundler/bundler/bundlets/alfred.bundler.sh: line 352: return: can only `return' from a function or sourced script
```

Clearly, the problem is in the bash bundler and in the fetching process.

**Comment by shawnrice** [comment]
It is... "ish."

So, we've switched to Github tags for releases (`major_version-latest`, `major_version-1`, `major_version-2`), which should make installing and upgrading easier, but, for development, it's a pain to push a tag each time, so each bundler now responds to an environmental variable called `AB_BRANCH`; if that is set, then it will grab the `head` rather than the tag. So, easier fixes: if you're running these from a shell, then just type `export AB_BRANCH='devel'` into the shell. Otherwise, set it in the script itself (for testing purposes). You can't do it through a subshell because the variable won't come back to the bundler itself.

What I've been doing for development is to head over to the tests directory and to copy a version of the bundlet into that directory and change the paths so that they use the ones relative to it. Then, I can make changes to the files and not have to reinstall the changes to test them. Just make sure that you have the environmental variable set to speed things along. The `-latest` tag on `devel` is sorely outdated (or maybe deleted... I can't remember).

**Comment by fractaledmind** [comment]
Ok. But this should not be a problem for the Applescript Bundler later, right? There will be tagged releases when it's out in the wild, so I won't need to manually export that var in the bundler proper?

Also, I exported the var and ran the command, partially successfully. Here's the return:

```
Macintosh-5:~ smargheim$ /bin/bash '/Users/smargheim/Documents/DEVELOPMENT/GitHub/alfred-bundler/bundler/bundlets/alfred.bundler.sh' utility Pashua latest false 
Alfred Bundler Error.... need an info.plist to use the bundler.
Print: Entry, ":name", Does Not Exist
Print: Entry, ":bundleid", Does Not Exist
Print: Entry, ":name", Does Not Exist
[14:54:30] [AlfredBundler.sh:128] [INFO] Loading utility 'Pashua' version latest ...
[14:54:30] [AlfredBundler.sh:144] [CRITICAL] Error: no valid JSON file found. This is a problem with the __implementation__ with the Alfred Bundler. Please let the workflow author know.
```

I'm assuming that my formulation of the command is off. This is what I am passing to `alfred.bundler.sh`, so what is malformed that is keeping this from working? (PS. I also tried "pashua" instead of "Pashua", both failed the same way)

**Comment by fractaledmind** [comment]
Also, I tried leaving off the `false` for the json var. Here's the error I got:

```
Macintosh-5:~ smargheim$ /bin/bash '/Users/smargheim/Documents/DEVELOPMENT/GitHub/alfred-bundler/bundler/bundlets/alfred.bundler.sh' utility Pashua latest
Alfred Bundler Error.... need an info.plist to use the bundler.
Print: Entry, ":name", Does Not Exist
Print: Entry, ":bundleid", Does Not Exist
Print: Entry, ":name", Does Not Exist
[14:58:00] [AlfredBundler.sh:128] [INFO] Loading utility 'Pashua' version latest ...
[14:58:00] [AlfredBundler.sh:203] [INFO] Installing utility 'Pashua' version latest ...

Fatal error: Uncaught exception 'Exception' with message 'Using the Alfred Bundler requires a valid info.plist file to be found; in other words, it needs to be used in a workflow. ' in /Users/smargheim/Library/Application Support/Alfred 2/Workflow Data/alfred.bundler-devel/bundler/AlfredBundler.php:195
Stack trace:
#0 /Users/smargheim/Library/Application Support/Alfred 2/Workflow Data/alfred.bundler-devel/bundler/AlfredBundler.php(172): AlfredBundlerInternalClass->setup()
#1 /Users/smargheim/Library/Application Support/Alfred 2/Workflow Data/alfred.bundler-devel/bundler/includes/install-asset.php(23): AlfredBundlerInternalClass->__construct()
#2 {main}
  thrown in /Users/smargheim/Library/Application Support/Alfred 2/Workflow Data/alfred.bundler-devel/bundler/AlfredBundler.php on line 195
```

**Comment by fractaledmind** [comment]
I'm sure that these errors are due to me not being up to speed; sorry if they are.

**Comment by shawnrice** [comment]
Do you have an `info.plist` file in the directory from which you're running the command?

**Comment by fractaledmind** [comment]
Let me work on testing the `alfred.bundler.scpt`, which is in a workflow dir, connection to `AlfredBundler.scpt`, which is in the bundler's dir. I'll get back with info

**Comment by fractaledmind** [comment]
Ok. So I set up a test workflow, which has in `info.plist` file right next to `bundler.scpt`. That script simply has this:

```
set b to load script "/Users/smargheim/Library/Application Support/Alfred 2/Workflow Data/alfred.bundler-devel/bundler/AlfredBundler.scpt"
b's load_utility("pashua", missing value, missing value)
```

When I run this, I get this error:

```
error "Alfred Bundler Error.... need an info.plist to use the bundler.
Print: Entry, \":name\", Does Not Exist
Print: Entry, \":bundleid\", Does Not Exist
Print: Entry, \":name\", Does Not Exist
[15:08:50] [AlfredBundler.sh:128] [INFO] Loading utility 'pashua' version latest ...
[15:08:50] [AlfredBundler.sh:203] [INFO] Installing utility 'pashua' version latest ..." number 1
```

You can see the code of `AlfredBundler.scpt` in the latest push.

When I run the same command from Terminal, I get this explicit error:

```
Fatal error: Uncaught exception 'Exception' with message 'Using the Alfred Bundler requires a valid info.plist file to be found; in other words, it needs to be used in a workflow. ' in /Users/smargheim/Library/Application Support/Alfred 2/Workflow Data/alfred.bundler-devel/bundler/AlfredBundler.php:195
Stack trace:
#0 /Users/smargheim/Library/Application Support/Alfred 2/Workflow Data/alfred.bundler-devel/bundler/AlfredBundler.php(172): AlfredBundlerInternalClass->setup()
#1 /Users/smargheim/Library/Application Support/Alfred 2/Workflow Data/alfred.bundler-devel/bundler/includes/install-asset.php(23): AlfredBundlerInternalClass->__construct()
#2 {main}
  thrown in /Users/smargheim/Library/Application Support/Alfred 2/Workflow Data/alfred.bundler-devel/bundler/AlfredBundler.php on line 195
```

This is the command: `'/Users/smargheim/Library/Application Support/Alfred 2/Workflow Data/alfred.bundler-devel/bundler/bundlets/alfred.bundler.sh' utility pashua latest`

I'm not really certain about the relation between Applescript and the shell. But it appears that `alfred.bundler.sh` won't work without an `info.plist` right next to it, or am I just crazy?

**Comment by fractaledmind** [comment]
NOTE: The command does work when I `cd` into the workflow directory and run the command. So, it must be something about the nature of Applescript's shells. Perhaps I could `cd` into the workflow directory in the `cmd` that i `do shell script` on? But how do I do that from the `AlfredBundler.scpt` in the bundler directory? How is it knowledgable of the calling scripts `pwd`?

**Comment by shawnrice** [comment]
Well, it won't work unless the current `pwd` has an `info.plist` file in it.

I setup a working directory for you in `tests/applescript`. You'll see an empty `test.scpt` file that you should use for implementation purposes (it's too much of a pain to run these from a workflow when testing). There's a modified version of the bash bundlet in the directory along with an `info.plist` and an `icon.png`. There is also an applescript bundlet there — with a few comments about things to change. Work from that one and then copy it over later. Work on the regular AlfredBundler.applescript file.

**Comment by shawnrice** [comment]
It's the nature of how shells work in general. When you run bash, php, python, ruby, etc... from the shell, then the working directory is the directory that you run the command from. If you look through a lot of the bundlers/bundlets, there are lines that get the path to the file themselves so they can use that as a jumping off point (PHP has `__FILE__` and `__DIR__`;  Ruby 1.9 and 2.0 have `__FILE__`; Ruby 2.0 has something like `__DIR__`; otherwise, for Ruby, I had to use `File.expand_path(File.dirname(__FILE__))`. For Bash, it's fucking terrible: `declare AB_ME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"`).

**Comment by shawnrice** [comment]
You probably know this one, but for AS: `set myPath to (path to me) as text`

**Comment by fractaledmind** [comment]
Ok. Let me make sure I get this, Workflow X (represented now by the test directory `tests/applescript/`) 
1. requires two scripts in order to use Alfred-Bundler's functionality: `alfred.bundler.scpt` and `alfred.bundler.sh`. For someone writing a workflow in Applescript, 
2. they will load the `alfred.bundler.scpt` script as a variable in their own script (let's call it `workflow.scpt`). 
3. That will allow them to call the utility and icon functions. In the `alfred.bundler.scpt` script, 
4. those functions are simple mirrors of/wrappers of the true functionality in `AlfredBundler.scpt`, which 
5. lives in Alfred-Bundler's directory. So, 
6. all that `alfred.bundler.scpt` actually natively does is check for the bundler's existence and download it if necessary and make `AlfredBundler.scpt`'s functions available to the workflow. This means that 
7. the actual utility installation (in this particular example) will take place in the bundler directory (by `AlfredBundler.scpt`). Now, 
8. `AlfredBundler.scpt` doesn't actually install uninstalled utilities, it sends a call to `alfred.bundler.sh`, in the bundlets directory, to do it. But, 
9. `alfred.bundler.sh` requires an `info.plist` file to exist in the working directory. So, 
10. I need to write the applescript bundler and bundlet in such a way that the working directory (the workflow's directory) is properly passed all the way to `alfred.bundler.sh` via 4 scripts (`workflow.scpt` -> `alfred.bundler.scpt` -> `AlfredBundler.scpt` -> `alfred.bundler.sh`)?

Are any of the 10 points unfounded or incorrect?

**Comment by shawnrice** [comment]
Mostly.
1. They have `workflow.scpt`, which loads `alfred.bundler.scpt` into a variable.
2. When the loading happens `alfred.bundler.scpt` looks to see if the bundler is installed; if not it:
3. Uses `alfred.bundler.sh` to install the bundler (just send `bash ./alfred.bundler.sh utility cocoaDialog` to make that happen)
4. Somehow, `alfred.bundler.scpt` then loads `AlfredBundler.scpt` into a variable and then passes all calls to that, which then are passed back to `alfred.bundler.scpt` and, ultimately, to `workflow.scpt`.

So, this implementation looks more like the PHP and Ruby bundlers in that both have a sort of "wrapper" class that then loads the actual bundler classes and passes all the calls to them. PHP accomplishes this because there is a `__call` function (magic) that I use to route to the internal bundler object. Ruby uses the `method_missing` function to pass everything to the internal class object as well.

So, I don't know if this is possible, but what you'd do is to load `alfred.bundler.scpt` into a variable (in `workflow.scpt`), then that variable would load `AlfredBundler.scpt` into a variable and pass everything to that variable and route the results back.

The `AlfredBundler.scpt` could then deal with the calls by looking to see if the asset exists, and, if not route the call to `SELF/bundlets/alfred.bundler.sh` and then reroute them back.

The install function in `alfred.bundler.scpt`, at least for now, would just be routed to the `alfred.bundler.sh` script that's in the same directory. Later, the AppleScript bundlet could be expanded to do the installation itself.

For now, if you develop in the `tests/applescript/` directory, then the necessary files would already be there, and you could just run it via the terminal via `osascript test.scpt`.

Does that help?

**Comment by shawnrice** [comment]
Oh, and for item four on your list (mirrors/wrappers), you'd need to figure out a way to route them to the Bundler backend. So, if AppleScript has something like PHP's `__call` or Ruby's `method_missing`, then you could use that. Otherwise, you'd have to make a wrapper function for each one that would then call the internal variable function.

Bash is weird because you can _very_ easily overwrite a function, which is why it has the functions as it does. However, those functions need to be declared because it would throw a `127` (command not found) error when the bundler was not installed, so it would prevent it from being installed... or at least they'd have to bootstrap it rather than just calling any functions.

**Comment by fractaledmind** [comment]
Ok. The issue is therefore that Applescript's `do shell script` does not pass the current working directory (the `load script` does however). I just pushed some scripts so that you can see it on your machine, but here's the breakdown:

From `testing.scpt`, I call `AlfredBundler.scpt`'s `test()` function. This, in turn, calls a shell script (`TEST.sh`) in the bundlets directory. `test()` returns the `pwd` for both Applescript and shell. If you run the code from `testing.scpt`, you will see something like this:

```
"Applescript PWD: /Users/smargheim/Documents/DEVELOPMENT/GitHub/alfred-bundler/tests/applescript/testing.scpt
Shell PWD: /"
```

So, we need to find a way to pass the pwd from the applescript to the shell, so that `alfred.bundler.sh` can check for an info.plist in the proper place. Would it be as simple as to have it check in `AB_ME`? It currently doesn't look like it does, or am I just wrong?

**Comment by shawnrice** [comment]
You couldn't tie it to `AB_ME` because that file might be somewhere else (it's sometimes called via `./bundlets/alfred.bundler.sh`).

Why not save the Applescript PWD as a variable and, for each shell script, do: `do shell script "cd " + APPLESCRIPT_PWD + "; the-rest-of-the-shell-script"`?

**Comment by fractaledmind** [comment]
Fuck. I had it right, but was trying to `cd` to a file...Anyway, things are on their way. Thanks.

**Comment by fractaledmind** [comment]
For `load_utility()`, should it only look in `alfred.bundler-devel/data/assets/utility/`, or should it also look in `alfred.bundler-devel/data/assets/applescript`?

**Comment by shawnrice** [comment]
Utilities are only in `utility`.

Basically, think of them as types: `applescript`, `bash`, `php`, `python`, `ruby`, `utility`. If you have something that isn't exactly an AppleScript library but is exclusively AppleScript, then you can make a subdirectory for them in the `applescript` directory. For Ruby, we have `ruby/gems`. Although, non-gems would be loaded with the same versioning: `ruby/{name}/{version}/{asset_goes_here}`.

A `load_utility` function would just call `load {utility} {other args}`. You could create a `load_library` function that would do the same but call `load {applescript} {other args}` For PHP and Ruby, those are just called `utility` and `library` rather than having the `load_` prefix.

**Comment by fractaledmind** [comment]
Alright. It is somewhat rudimentary, and dependent on the bash bundler and bundlet, but the AppleScript bundler/bundlet would appear to be basically done. I need to add a more consistent error system, and will fully implement the error code scheme that is almost done for the bash bundler. Aside from consistent error codes, however, things look stable for me so far.

The bundlet is merely a portal to the bundler, which has 3 primary API functions:
1. `library(name, version, json)` to load the script object of an AppleScript library/script
2. `utility(name, version, json)` to return the invoke path to a command line utility
3. `icon(font, name, color, alter)` to return the path to the icon file

It also has a number of helper functions which workflow authors can easily hook into for certain IO and String functionality. For Taurus 1, the AppleScript bundlet will require the bash bundlet as a companion (only for bootstraping).

I will continue to test various combinations for the 3 API functions, and someone else should too. But the main guts are all there.

**Comment by shawnrice** [comment]
Let's one up this thing and give the bundlet its own installation function. Can you adapt this:

```
set _major_version to "devel"
set _home to (path to home folder as Unicode text)
set _data to _home & "Library:Application Support:Alfred 2:Workflow Data:alfred.bundler-" & _major_version
set _cache to _home & "Library:Caches:com.runningwithcrayons.Alfred-2:Workflow Data:alfred.bundler-" & _major_version


if not (exists (_data as alias)) then return true

-- we need to install the Bundler
try
    get_install_confirmation()
on error
    --- we did not get permission to continue to install the bundler
    return false
end try

--- download the bundler
set _suffix to ".zip"
set AppleScript's text item delimiters to ","

set URLs to {"https://github.com/shawnrice/alfred-bundler/archive/" & _major_version & _suffix, "https://bitbucket.org/shawnrice/alfred-bundler/get/" & _major_version & _suffix}
set _zipfile to (quoted form of POSIX path of _cache) & "/installer/bundler.zip"
repeat with _url in URLs
    set _status to (do shell script "curl -fsSL --create-dirs --connect-timeout 5 " & _url & " -o " & _zipfile & " && echo $?")
    if _status is equal to "0" then exit repeat
end repeat

--- we could not download the file
if _status is not equal to "0" then error "Could not download bundler install file" number 23

set _cmd to "cd " & (quoted form of POSIX path of _cache) & "; cd installer; unzip -qo bundler.zip; mv ./*/bundler " & (quoted form of POSIX path of _data)

do shell script _cmd

--- function to get confirmation to install the bundler
on get_install_confirmation()
    set _plist to POSIX path of (path to me) as Unicode text --- "info.plist"
    set _dir to do shell script "dirname '" & _plist & "'"
    set _plist to _dir & "/info.plist"
    set _cmd to "/usr/libexec/PlistBuddy -c 'Print :name' '" & _plist & "'"
    set _name to do shell script _cmd
    set _icon to ((path to me as text) & "::icon.png")

    try
        --- This is redundant, and there probably is a better way...
        if exists _icon as alias then set _icon to _icon as alias
    on error
        set _icon to "System:Library:CoreServices:CoreTypes.bundle:Contents:Resources:SideBarDownloadsFolder.icns" as alias
    end try

    set _text to _name & " needs to install additional components, which will be placed in the Alfred storage directory and will not interfere with your system.

    You may be asked to allow some components to run, depending on your security settings.

    You can decline this installation, but " & _name & " may not work without them. There will be a slight delay after accepting."

    display dialog _text buttons {"More Info", "Cancel", "Proceed"} default button 3 with title "Setup " & _name with icon _icon
    set _response to button returned of result
    if _response is equal to "Proceed" then return true
    if _response is equal to "More Info" then
        tell application "System Events"
            open location "https://github.com/shawnrice/alfred-bundler/wiki/What-is-the-Alfred-Bundler"
        end tell
        error "User looked sought more information" number 23
    end if
    if _response is equal to "Cancel" then error "User canceled installation" number 23
end get_install_confirmation
```

Then, the bash bundlet that it needed during runtime would just be the one at `bundler_data_dir/bundler/bundlets/alfred.bundler.sh`.

**Comment by fractaledmind** [comment]
Ok. Commit 74da5745368bf423d7557fb83c7af1524968daed adds my version of `_bootstrap()` to the `alfred.bundler.scpt` file. I have tested it multiple times (with good internet), and it works well. One question, why catch the errors in `get_installation_confirmation()` in the `_bootstrap()` function? I've gone ahead and left it in, but it doesn't make sense to me. Shouldn't we let those errors kill the script?

**Comment by fractaledmind** [comment]
Also, shouldn't we add some code to delete the cached bundler zip and unzipped files after the bundler files have been moved to the Bundler directory? Or should they remain in the cache?

**Comment by shawnrice** [comment]
Those files should be deleted. You're right.

The thing about catching errors is to let the workflow author decide how to recover from them. I might have layered the errors a bit too much. All of the bundlers are set up the same way to throw the potentially recoverable errors. It's a harder with bash (they'd have to set a trap).

**Comment by fractaledmind** [comment]
Added unit tests for the AppleScript bundler/bundlet in commit 0eacb122249911ab4b7322804bc4d8e3465eef73. Then fixed all paths so that the tests can work on anyone's machines in commit feec60ddc8ec10a5830fb891d15ec00fc8559c8a. 

Please test on your machines.

**Comment by shawnrice** [comment]
So, it seems like the only thing that's really left (assuming that the unit tests have sufficient coverage) is to do the documentation.

I don't think that there are any auto-api documentation generators for AppleScript, so we'll probably fallback to just a "general" documentation (I think we're going to do this for Bash too because it doesn't seem like there are any suitable ones that I've found yet).

**Comment by fractaledmind** [comment]
Internally, I've mirrored Python Sphinx documentation style. So maybe I can get partially there using that.

The only thing the tests don't currently have is incorrect version number. I was waiting to put them in until the bash bug was fixed.

**Comment by shawnrice** [comment]
I'll get to the bash bug soon. Right now my head is back in Ruby trying to figure out something that I've broken. Yay!

**Comment by shawnrice** [comment]
@smargh : is this done? The documentation on the defaults included can be moved to the bundler docs issue queue. If it is done, then go ahead and close it.

**Comment by shawnrice** [comment]
I don't think that we need to document the libraries that are available because they're on the defaults page with links to the libraries themselves for new documentation. Since we just closed the log issue, I'm assuming that it's done here too, so I'm closing this. If that's premature, then re-open.
